name: 自动续时蓝天云

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 22 * * *' # 每天一次，UTC 时间晚上 10 点运行（即北京时间早上 6 点）
  workflow_dispatch:

jobs:
  read-and-access:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: 从文件读取需要续费的ID
      run: |
        sudo apt-get install -y jq
        echo "211.101.232.180 lantian.simpfun.cn" | sudo tee -a /etc/hosts
        renew_list=$(jq -r '.[]' renewid.json)

        for hid in $renew_list; do
          echo "即将续费ID: $hid"
          url="http://lantian.simpfun.cn/addons?_plugin=3&_controller=index&_action=addhelp&hid=$hid"
          response=$(curl -s "$url")
          if echo "$response" | grep -q '请到期前两天再来续时哦'; then
            echo "ID $hid 未到期"
          else
          echo "内容返回 $hid: $response"
          fi
        done
